import { useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';

type IconName = 'book'|'practice'|'test'|'chart'|'target'|'flame'|'note'|'flash'|'doubt'|'calendar'|'arrow'|'check'|'play'|'menu'|'close'|'layers';

function Icon({name,size=21}:{name:IconName;size?:number}) {
  const p={width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true};
  const d:Record<IconName,ReactNode>={
    book:<><path d="M5 4.5A2.5 2.5 0 0 1 7.5 2H20v18H7.5A2.5 2.5 0 0 0 5 22Z"/><path d="M5 4.5V22"/></>,
    practice:<><circle cx="12" cy="12" r="8"/><path d="M8 12h8M12 8v8"/></>,
    test:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h8M8 15h5"/></>,
    chart:<><path d="M4 19V5M4 19h16"/><path d="m7 15 4-4 3 2 5-7"/></>,
    target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/></>,
    flame:<><path d="M12 21c4 0 7-2.7 7-6.6 0-3.4-2.2-5.9-4.4-8.4-.2 2-1 3.3-2.1 4.3.2-3.5-1.8-6.1-4.2-8.3.1 3.5-3.3 5.7-3.3 10.2C5 18 8 21 12 21Z"/></>,
    note:<><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h4"/></>,
    flash:<><path d="M12 2 5 13h6l-1 9 7-11h-6l1-9Z"/></>,
    doubt:<><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.7 2.7 0 1 1 4.3 2.2c-1 .7-1.8 1.1-1.8 2.8M12 17h.01"/></>,
    calendar:<><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 10h16"/></>,
    arrow:<><path d="M5 12h13"/><path d="m13 6 6 6-6 6"/></>,
    check:<path d="m5 12 4 4L19 6"/>,
    play:<path d="m9 6 9 6-9 6V6Z"/>,
    menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>,
    close:<><path d="m6 6 12 12M18 6 6 18"/></>,
    layers:<><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></>,
  };
  return <svg {...p}>{d[name]}</svg>;
}

const goApp=()=>{window.location.href='/';};

const features=[
  ['practice','Practice','Chapter-wise questions, focused sessions and daily practice.','#805be6'],
  ['test','Mock Tests','A proper test experience to build speed, accuracy and confidence.','#438fe8'],
  ['flame','Daily DPP','A small daily question block that keeps preparation moving.','#e8a43d'],
  ['target','Mistake Book','Keep the questions you got wrong close for another look.','#45c894'],
  ['note','Revision','Saved questions, notes and quick revision tools in one place.','#e685ae'],
  ['chart','Progress','See accuracy, attempts and subject-wise preparation over time.','#4fc7e5'],
] as const;

const tools=[
  ['book','Question Bank'],['layers','PYQs'],['flash','Flashcards'],['note','NCERT Mode'],
  ['calendar','Study Planner'],['doubt','Doubt Centre'],['chart','Performance'],['target','Mistake Book'],
] as const;

export default function WebsiteHome(){
  const [mobile,setMobile]=useState(false);
  const jump=(id:string)=>{setMobile(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};

  const css=`\
    .np-site{--bg:#070d10;--surface:#10181c;--surface2:#151f24;--text:#f4f7f6;--muted:#8e9ba0;--line:rgba(255,255,255,.075);--gold:#eab550;--mint:#59d3c1;min-height:100vh;background:radial-gradient(850px 500px at 76% -8%,rgba(234,181,80,.09),transparent 65%),radial-gradient(760px 480px at -5% 25%,rgba(89,211,193,.055),transparent 68%),var(--bg);color:var(--text);font-family:'DM Sans',system-ui,sans-serif;overflow:hidden}.np-wrap{width:min(1160px,calc(100% - 56px));margin:auto}
    .np-nav{position:sticky;top:0;z-index:50;background:rgba(7,13,16,.78);border-bottom:1px solid rgba(255,255,255,.06);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px)}.np-navin{height:68px;display:flex;align-items:center;justify-content:space-between;gap:24px}.np-brand{display:flex;align-items:center;gap:10px}.np-logo{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(145deg,#ffd879,#e1a23c);color:#17130a;font:950 15px Manrope;box-shadow:0 8px 24px rgba(233,180,79,.14)}.np-brand b{font:800 20px Manrope;letter-spacing:-.8px}.np-brand b span{color:var(--gold)}.np-navlinks{display:flex;gap:2px;padding:4px;border:1px solid rgba(255,255,255,.055);border-radius:12px;background:rgba(255,255,255,.025)}.np-navlinks button,.np-login{border:0;background:transparent;color:#96a2a7;padding:8px 12px;border-radius:9px;font-size:9px;font-weight:800}.np-navlinks button:hover{background:rgba(255,255,255,.06);color:#fff}.np-navactions{display:flex;align-items:center;gap:6px}.np-login:hover{color:#fff}.np-open,.np-primary{border:0;border-radius:11px;background:var(--gold);color:#17130a;font-weight:950}.np-open{padding:10px 13px;font-size:9px}.np-mobile{display:none;border:1px solid rgba(255,255,255,.08);background:#131a1e;color:#fff;width:39px;height:39px;border-radius:11px}
    .np-hero{padding:86px 0 72px}.np-herogrid{display:grid;grid-template-columns:minmax(0,1fr) minmax(390px,.88fr);align-items:center;gap:62px}.np-eyebrow{display:inline-flex;align-items:center;gap:7px;padding:6px 9px;border-radius:999px;border:1px solid rgba(89,211,193,.16);background:rgba(89,211,193,.055);color:#8fd6cb;font-size:7px;font-weight:950;letter-spacing:1.45px}.np-eyebrow i{width:6px;height:6px;border-radius:50%;background:var(--mint);box-shadow:0 0 13px rgba(89,211,193,.65)}.np-hero h1{font:800 clamp(49px,6.1vw,78px)/.94 Manrope;letter-spacing:-4px;margin:21px 0 18px;max-width:730px}.np-hero h1 span{color:var(--gold)}.np-herotext{max-width:570px;color:#99a6ab;font-size:14px;line-height:1.72}.np-actions{display:flex;gap:9px;margin-top:26px}.np-primary{display:inline-flex;align-items:center;gap:8px;padding:13px 16px;font-size:9px;box-shadow:0 13px 30px rgba(233,180,79,.13);transition:.18s ease}.np-primary:hover{transform:translateY(-1px);box-shadow:0 16px 34px rgba(233,180,79,.18)}.np-secondary{border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.035);color:#e8ecee;border-radius:11px;padding:12px 15px;font-size:9px;font-weight:900}.np-secondary:hover{background:rgba(255,255,255,.06)}.np-trust{display:flex;flex-wrap:wrap;gap:14px;margin-top:21px;color:#758389;font-size:8px}.np-trust b{color:var(--mint);margin-right:5px}
    .np-art{position:relative;height:555px;display:flex;align-items:center;justify-content:center}.np-art:before{content:"";position:absolute;width:470px;height:470px;border-radius:50%;border:1px solid rgba(89,211,193,.08);box-shadow:0 0 0 55px rgba(89,211,193,.018),0 0 0 110px rgba(234,181,80,.012)}.np-phone{position:absolute;right:7%;width:296px;height:540px;border-radius:39px;background:#050809;border:7px solid #1b2428;box-shadow:0 38px 90px rgba(0,0,0,.5),0 0 0 1px rgba(255,255,255,.055);transform:rotate(2.5deg)}.np-notch{position:absolute;top:8px;left:50%;transform:translateX(-50%);width:94px;height:22px;border-radius:14px;background:#050708;z-index:3}.np-screen{position:absolute;inset:0;border-radius:30px;overflow:hidden;padding:42px 17px 17px;background:linear-gradient(180deg,#10181c,#0a1013)}.np-minitop{display:flex;align-items:center;justify-content:space-between}.np-minibrand{display:flex;align-items:center;gap:6px;font:800 10px Manrope}.np-minin{width:20px;height:20px;border-radius:7px;display:grid;place-items:center;background:var(--gold);color:#151109;font-size:9px}.np-pill{font-size:7px;color:#e9b44f;background:rgba(233,180,79,.08);padding:5px 7px;border-radius:999px}.np-mini-k{display:block;color:#718087;font-size:6px;letter-spacing:1px;font-weight:950;margin-top:18px}.np-mini-title{font:800 25px/1 Manrope;letter-spacing:-1.2px;margin-top:7px}.np-minihero{margin-top:17px;padding:15px;border-radius:18px;background:linear-gradient(135deg,#163b3d,#192332);border:1px solid rgba(89,211,193,.18);box-shadow:inset 0 1px rgba(255,255,255,.04)}.np-minihero h3{font:800 17px/1.08 Manrope;letter-spacing:-.6px;margin:7px 0}.np-minihero p{font-size:7px;color:#9cb0b2;line-height:1.55}.np-minibtn{display:inline-block;margin-top:7px;background:#f4f6f4;color:#121719;border-radius:8px;padding:7px 9px;font-size:7px;font-weight:950}.np-minigrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.np-minicard{padding:10px;border-radius:13px;background:#12191d;border:1px solid rgba(255,255,255,.055)}.np-minicard b{display:block;font-size:8px;margin-top:7px}.np-minicard small{display:block;color:#748187;font-size:6px;margin-top:2px}.np-miniicon{width:27px;height:27px;border-radius:9px;display:grid;place-items:center}.np-p{background:rgba(138,103,232,.18);color:#a98eef}.np-b{background:rgba(78,147,232,.17);color:#70a9ed}.np-o{background:rgba(233,180,79,.15);color:#e9b44f}.np-g{background:rgba(87,209,191,.15);color:#57d1bf}.np-sticker{position:absolute;left:1%;bottom:23px;width:180px;padding:15px 16px;border-radius:17px;background:rgba(15,23,27,.94);border:1px solid rgba(255,255,255,.08);box-shadow:0 18px 50px rgba(0,0,0,.28);transform:rotate(-3deg)}.np-sticker b{font:800 26px Manrope;color:var(--gold);display:block}.np-sticker span{display:block;color:#87949a;font-size:8px;margin-top:2px}
    .np-section{padding:86px 0;border-top:1px solid rgba(255,255,255,.045)}.np-sectionhead{display:flex;justify-content:space-between;align-items:flex-end;gap:30px;margin-bottom:28px}.np-sectionhead small{color:#78878d;font-size:7px;letter-spacing:1.5px;font-weight:950}.np-sectionhead h2{font:800 clamp(31px,4vw,44px)/1 Manrope;letter-spacing:-1.9px;margin:7px 0 0}.np-sectionhead p{max-width:430px;color:#89969b;font-size:10px;line-height:1.7;margin:0}.np-features{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.np-feature{min-height:180px;padding:20px;border-radius:19px;background:#10181c;border:1px solid rgba(255,255,255,.065);position:relative;overflow:hidden;transition:.2s ease}.np-feature:hover{transform:translateY(-3px);border-color:rgba(255,255,255,.13);background:#131c20;box-shadow:0 18px 40px rgba(0,0,0,.15)}.np-feature:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-80px;top:-85px;background:var(--tone);opacity:.08}.np-ficon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;color:var(--tone);background:color-mix(in srgb,var(--tone) 10%,transparent);border:1px solid color-mix(in srgb,var(--tone) 18%,transparent)}.np-feature h3{font:800 17px Manrope;letter-spacing:-.5px;margin:18px 0 7px}.np-feature p{color:#859197;font-size:9px;line-height:1.65;max-width:300px}
    .np-subjects{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.np-subject{padding:21px;border-radius:20px;background:#10181c;border:1px solid rgba(255,255,255,.065);position:relative;overflow:hidden}.np-letter{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:color-mix(in srgb,var(--tone) 13%,transparent);color:var(--tone);font:900 15px Manrope;border:1px solid color-mix(in srgb,var(--tone) 18%,transparent)}.np-subject h3{font:800 19px Manrope;margin:17px 0 5px}.np-subject p{color:#859197;font-size:9px;margin:0}.np-line{height:4px;border-radius:999px;background:rgba(255,255,255,.055);margin-top:22px;overflow:hidden}.np-line i{display:block;width:42%;height:100%;border-radius:inherit;background:var(--tone)}
    .np-journey{display:grid;grid-template-columns:1.05fr .95fr;gap:10px}.np-jcard{padding:24px;border-radius:21px;background:#10181c;border:1px solid rgba(255,255,255,.065)}.np-jcard.colour{background:linear-gradient(135deg,#122c31,#191b28);border-color:rgba(89,211,193,.14)}.np-jcard h3{font:800 27px/1.06 Manrope;letter-spacing:-1.1px;margin:14px 0 8px}.np-jcard>p{color:#89969b;font-size:10px;line-height:1.65;max-width:500px}.np-steps{display:grid;gap:7px;margin-top:20px}.np-step{display:flex;gap:11px;align-items:center;padding:11px;border-radius:13px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.05)}.np-stepnum{font:800 8px ui-monospace,monospace;color:var(--gold)}.np-step b{display:block;font-size:9px}.np-step span:last-child{display:block;color:#77858b;font-size:7px;margin-top:2px}.np-tools{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:18px}.np-tool{padding:11px 12px;border-radius:13px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.055)}.np-toolicon{width:31px;height:31px;border-radius:9px;display:grid;place-items:center;background:rgba(255,255,255,.06);margin-bottom:8px;color:var(--gold)}.np-tool b{font-size:8px}.np-tool span{display:block;color:#7e8b91;font-size:6px;margin-top:3px}
    .np-cta{margin:28px 0 72px;padding:48px;border-radius:25px;background:linear-gradient(135deg,#142d31,#1b1d2c);border:1px solid rgba(234,181,80,.16);position:relative;overflow:hidden;box-shadow:0 24px 65px rgba(0,0,0,.18)}.np-cta:before{content:"";position:absolute;width:500px;height:500px;border-radius:50%;right:-230px;top:-260px;border:1px solid rgba(234,181,80,.12);box-shadow:0 0 0 55px rgba(234,181,80,.015)}.np-cta h2{font:800 40px/1 Manrope;letter-spacing:-1.8px;margin:0 0 8px;position:relative}.np-cta p{max-width:590px;color:#99a6ab;font-size:10px;line-height:1.7;position:relative}.np-cta button{position:relative;margin-top:13px}.np-footer{border-top:1px solid rgba(255,255,255,.055);padding:28px 0 42px}.np-footin{display:flex;justify-content:space-between;gap:20px}.np-footin p{max-width:390px;color:#758187;font-size:8px;line-height:1.6}.np-footlinks{display:flex;gap:16px;align-items:flex-start}.np-footlinks button{border:0;background:none;color:#87949a;font-size:8px;font-weight:800}.np-footlinks button:hover{color:#fff}
    @media(max-width:900px){.np-herogrid{grid-template-columns:1fr;gap:10px}.np-art{height:535px}.np-phone{right:13%}.np-sticker{left:8%}.np-features{grid-template-columns:1fr 1fr}.np-subjects{grid-template-columns:1fr}.np-journey{grid-template-columns:1fr}.np-sectionhead{align-items:flex-start;flex-direction:column;gap:9px}}
    @media(max-width:680px){.np-wrap{width:calc(100% - 28px)}.np-navin{height:60px}.np-navlinks,.np-navactions{display:none}.np-mobile{display:grid;place-items:center}.np-mobilemenu{display:grid;gap:5px;padding:9px 14px 14px;background:#0a0f12;border-top:1px solid rgba(255,255,255,.05)}.np-mobilemenu button{border:0;border-radius:10px;background:#11181c;color:#dce2e4;padding:11px;text-align:left;font-size:9px;font-weight:800}.np-mobilemenu .cta{background:#e9b54f;color:#17130a}.np-hero{padding:58px 0 48px}.np-hero h1{font-size:47px;letter-spacing:-2.7px}.np-herotext{font-size:12px}.np-actions{flex-direction:column}.np-primary,.np-secondary{justify-content:center;width:100%}.np-art{height:480px;margin-top:10px}.np-phone{width:260px;height:470px;right:4%}.np-sticker{left:0;bottom:15px;width:145px}.np-section{padding:58px 0}.np-sectionhead h2{font-size:31px}.np-features{grid-template-columns:1fr}.np-feature{min-height:150px}.np-jcard{padding:20px}.np-tools{grid-template-columns:1fr 1fr}.np-cta{padding:30px 21px;margin-bottom:55px}.np-cta h2{font-size:29px}.np-footin{flex-direction:column}.np-footlinks{flex-wrap:wrap}}

  `;

  return <div className="np-site"><style>{css}</style>
    <nav className="np-nav"><div className="np-wrap np-navin">
      <a className="np-brand" href="/" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}}><span className="np-logo">N</span><b>neet<span>prep</span></b></a>
      <div className="np-navlinks"><button onClick={()=>jump('features')}>Features</button><button onClick={()=>jump('subjects')}>Subjects</button><button onClick={()=>jump('journey')}>How it works</button></div>
      <div className="np-navactions"><button className="np-login" onClick={goApp}>Log in</button><button className="np-open" onClick={goApp}>Open NEETPrep →</button></div>
      <button className="np-mobile" onClick={()=>setMobile(v=>!v)} aria-label="Menu"><Icon name={mobile?'close':'menu'} size={18}/></button>
    </div>{mobile&&<div className="np-mobilemenu"><button onClick={()=>jump('features')}>Features</button><button onClick={()=>jump('subjects')}>Subjects</button><button onClick={()=>jump('journey')}>How it works</button><button className="cta" onClick={goApp}>Open NEETPrep →</button></div>}</nav>

    <section className="np-hero"><div className="np-wrap np-herogrid"><div>
      <span className="np-eyebrow"><i/> BUILT FOR NEET UG PREPARATION</span>
      <h1>Prepare every day.<br/><span>Progress every week.</span></h1>
      <p className="np-herotext">NEETPrep brings practice, daily questions, mock tests, revision and progress together in one focused study platform.</p>
      <div className="np-actions"><button className="np-primary" onClick={goApp}>Start Practicing <Icon name="arrow" size={14}/></button><button className="np-secondary" onClick={()=>jump('features')}>Explore NEETPrep</button></div>
      <div className="np-trust"><span><b>✓</b>Practice questions</span><span><b>✓</b>NTA-style tests</span><span><b>✓</b>Personal progress</span><span><b>✓</b>One focused workspace</span></div>
    </div><div className="np-art" aria-hidden="true">
      <div className="np-phone"><div className="np-notch"/><div className="np-screen"><div className="np-minitop"><div className="np-minibrand"><span className="np-minin">N</span>neetprep</div><span className="np-pill">🔥 7 days</span></div><span className="np-mini-k">NEET UG 2027 · DAILY PREP</span><div className="np-mini-title">What are we<br/>solving today?</div><div className="np-minihero"><span className="np-mini-k">TODAY'S DPP</span><h3>20 questions.<br/>20 focused minutes.</h3><p>A small block to keep your preparation moving every day.</p><span className="np-minibtn">Start DPP →</span></div><div className="np-minigrid">
        <div className="np-minicard"><div className="np-miniicon np-p"><Icon name="practice" size={14}/></div><b>Practice</b><small>10 questions</small></div>
        <div className="np-minicard"><div className="np-miniicon np-b"><Icon name="test" size={14}/></div><b>Mock Tests</b><small>Real exam flow</small></div>
        <div className="np-minicard"><div className="np-miniicon np-o"><Icon name="book" size={14}/></div><b>Saved</b><small>Revise later</small></div>
        <div className="np-minicard"><div className="np-miniicon np-g"><Icon name="target" size={14}/></div><b>Mistakes</b><small>Repair weak spots</small></div>
      </div></div></div><div className="np-sticker"><b>720</b><span>marks in the NEET pattern</span></div>
    </div></div></section>

    <section className="np-section" id="features"><div className="np-wrap"><div className="np-sectionhead"><div><small>ONE PREP SPACE</small><h2>Everything you need to study.</h2></div><p>No complicated setup. Pick what you need, solve, review, and get back to preparation.</p></div>
      <div className="np-features">{features.map(([icon,title,text,tone])=><article key={title} className="np-feature" style={{'--tone':tone} as CSSProperties}><div className="np-ficon"><Icon name={icon} size={21}/></div><h3>{title}</h3><p>{text}</p></article>)}</div>
    </div></section>

    <section className="np-section" id="subjects"><div className="np-wrap"><div className="np-sectionhead"><div><small>YOUR NEET SYLLABUS</small><h2>Three subjects. One clear system.</h2></div><p>Each subject gets its own identity while the overall experience stays consistent.</p></div>
      <div className="np-subjects">{[['P','Physics','Concepts · Numericals · Practice','#438fe8'],['C','Chemistry','Physical · Organic · Inorganic','#45c9b5'],['B','Biology','Botany · Zoology · NCERT','#4dc88e']].map(([letter,name,text,tone])=><article className="np-subject" key={name} style={{'--tone':tone} as CSSProperties}><div className="np-letter">{letter}</div><h3>{name}</h3><p>{text}</p><div className="np-line"><i/></div></article>)}</div>
    </div></section>

    <section className="np-section" id="journey"><div className="np-wrap"><div className="np-sectionhead"><div><small>THE DAILY LOOP</small><h2>Simple enough to actually use.</h2></div><p>The product should help a student decide what to do next, not make them study the interface.</p></div>
      <div className="np-journey"><article className="np-jcard colour"><span className="np-eyebrow">YOUR DAY</span><h3>Open. Practice.<br/>Review. Repeat.</h3><p>Start with a daily target, continue your preparation, or jump straight into a test when you're ready.</p><div className="np-steps"><div className="np-step"><span className="np-stepnum">01</span><div><b>Choose today's work</b><span>DPP, practice or revision</span></div></div><div className="np-step"><span className="np-stepnum">02</span><div><b>See what happened</b><span>Accuracy and mistakes</span></div></div><div className="np-step"><span className="np-stepnum">03</span><div><b>Come back tomorrow</b><span>Keep your streak moving</span></div></div></div></article>
        <article className="np-jcard"><span className="np-eyebrow" style={{color:'#e9b54f',background:'rgba(233,181,79,.08)',borderColor:'rgba(233,181,79,.14)'}}>STUDY CENTRE</span><h3>A bigger toolkit, when you need it.</h3><p>Keep the home experience focused. Open the Study Centre when you want the full preparation toolbox.</p><div className="np-tools">{tools.map(([icon,title])=><div className="np-tool" key={title}><div className="np-toolicon"><Icon name={icon} size={15}/></div><b>{title}</b><span>Inside the student app</span></div>)}</div></article>
      </div>
    </div></section>

    <section className="np-wrap"><div className="np-cta"><h2>Your next question is waiting.</h2><p>Open NEETPrep and turn today's preparation into one more solved question, one more reviewed mistake, and one more step forward.</p><button className="np-primary" onClick={goApp}>Open NEETPrep <Icon name="arrow" size={14}/></button></div></section>

    <footer className="np-footer"><div className="np-wrap np-footin"><div><a className="np-brand" href="/"><span className="np-logo">N</span><b>neet<span>prep</span></b></a><p>A focused NEET UG preparation platform for practice, tests, revision and progress.</p></div><div className="np-footlinks"><button onClick={()=>jump('features')}>Features</button><button onClick={()=>jump('subjects')}>Subjects</button><button onClick={()=>jump('journey')}>How it works</button><button onClick={goApp}>Student App</button></div></div></footer>
  </div>;
}
